# This is a basic configuration example for SpaceVim

# All SpaceVim options are below [options] snippet
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer, the value of this option is a string.
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors, the type of the value is boolean, true or false.
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    # Display file type icon on the tabline, If you do not have nerd fonts
    # installed, please change the value to false
    enable_tabline_filetype_icon = true
    # Display current mode text on statusline, by default It is disabled,
    # only color will be changed when switch modes.
    enable_statusline_mode = true
    automatic_update = true
    relativenumber = false
[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "smart"
    #bootstrap_after="s#cargo_task" 

[[layers]]
    name = "shell"
    default_position = "top"
    default_height = 30

[[layers]]
  name = "lang#rust"
  format_on_save = true
  recommended_style = true
[[layers]]
  name = 'gtags'
  gtagslabel = "ctags"
[[layers]]
  name = "lsp"
  enabled_clients = [ "rust_analyzer", "pyright" ]
[[layers]]
  name = "denite"
[[layers]]
  name = 'git'
[[layers]]
  name = 'VersionControl'
# [[layers]]
  # name = "lang#python"
  # enable_typeinfo = true
  # format_on_save = true
  # enabled_linters = ['python', 'pylint']
[[layers]]
  name = 'lang#c'
  enable_clang_syntax_highlight = true
  format_on_save = true
[[layers]]
  name = "lang#toml"
[[layers]]
  name = "treesitter"
[[layers]]
  name = "debug"
[[layers]]
  name = "github"
[[layers]]
  name = "sudo"
