[registries.crates-io]
protocol = "sparse"

[target.x86_64-unknown-linux-gnu]
rustc-wrapper = "sccache"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
[build]
rustflags = ["--cfg", "tokio_unstable"]
[profile.release]
lto = true
opt-level = 2
target-cpu = "native"
