[registries.crates-io]
protocol = "sparse"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "--cfg", "tokio_unstable"]
[build]
rustc-wrapper = "sccache"
rustflags = ["--cfg", "tokio_unstable"]
[profile.release]
lto = "thin"
opt-level = 2
